CREATE TABLE INFORMATION(
FIRSTNAME NVARCHAR(50) NOT NULL,
LASTNAME nvarchar(10) NOT NULL,
ADDRESS nvarchar(50) NOT NULL,
CITY NVARCHAR(10) NOT NULL,
AGE INT NOT NULL
);

SELECT * FROM INFORMATION

INSERT INTO INFORMATION VALUES("MICKEY","MOUSE","123 FANSTASY WAY","SURAT",73);
INSERT INTO INFORMATION VALUES("BAT","MAN","321 CAVERN AVE","GOTHAM",54);
INSERT INTO INFORMATION VALUES("WONDER","WOMAN","987 TRUTH AWAY","PARADAISE",39);
INSERT INTO INFORMATION VALUES("DONALND","DUCK","555 QWACK STREET","MALLARD",65);
INSERT INTO INFORMATION VALUES("BUGS","BUNNY","657 CARROT STREET","RASCAL",58);
INSERT INTO INFORMATION VALUES("WILLEY","COYOTE","999 ACME WAY","CANYON",61);
INSERT INTO INFORMATION VALUES("CAT","WOMAN","234 PURRFECT STREET","HAIRBALL",32);
INSERT INTO INFORMATION VALUES("TWEETY","BIRD","543 RADHIKA OPTIMA","YAMUNA",28);